### ISSUE TITLE
Sprint 6: 3. Refactoring

### ISSUE THREAD

**Issue by variableVG** [variableVG/swkom_project#134]
![Image](https://user-images.githubusercontent.com/58001220/205674695-0bfa51c1-eb4f-41ae-b454-9f9f46a647c8.png)

**Comment by i-nazuma** [comment]
Are the 2 LocalDateConverter Classes in the configuration package used? I didn't find a use case but maybe the API uses it. that's why I'm asking..

and then if we delete all the services + impl classes except parcel and warehouse this task is done I believe

**Comment by variableVG** [comment]
Hi! The files in the Configuration Folder were automatically generated at the beginning of the project, when we created the project with the docker file. As far as I know we do not use them, unless Swagger uses that. You can try to delete them and see what happens ... if you break the project, then put them back !

The impl classes can be deleted except the warehouse and parcel.
