### ISSUE TITLE
We had to change ParcelImpl and WarehouseImpl to ParcelService and WarehouseServiceImp. Should we do that with the rest of classes

### ISSUE THREAD

**Issue by variableVG** [variableVG/swkom_project#97]
In Sprint 3 we had missing: 

- File at/fhtw/swen3/services/impl/ParcelServiceImpl.java is missing! (-4,00)
- File at/fhtw/swen3/services/impl/WarehouseServiceImpl.java is missing! (-4,00)

But the rest of classes were not missing. Therefore my question: Should we change also HopImpl -> HopServiceImpl, GeocoordinateImp -> GeocoordinateServiceImpl and so on ???

**Comment by i-nazuma** [comment]
Yes absolutely, for a standardized naming convention. I refactored and renamed the rest of the classes in my last commit to the dev branch.
